version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./sql:/var/lib/mysql7"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  server:
    build: .
    volumes:
      - ./:/go/src
    environment:
      CONFIG_ENV: "local"
    depends_on:
      - mysql
    ports:
      - "8080:8080"
